import { PDA } from '../types';

export const PDA_EXAMPLES: Record<string, PDA> = {
  pda1: {
    states: [
      { id: 'Q0', label: 'Q0', isStart: true, isAccept: false },
      { id: 'Q1', label: 'Q1', isStart: false, isAccept: false },
      { id: 'Q2', label: 'Q2', isStart: false, isAccept: false },
      { id: 'Q3', label: 'Q3', isStart: false, isAccept: false },
      { id: 'Q4', label: 'Q4', isStart: false, isAccept: false },
      { id: 'Q5', label: 'Q5', isStart: false, isAccept: false },
      { id: 'Q6', label: 'Q6', isStart: false, isAccept: false },
      { id: 'Q7', label: 'Q7', isStart: false, isAccept: false },
      { id: 'Q8', label: 'Q8', isStart: false, isAccept: false },
      { id: 'Q9', label: 'Q9', isStart: false, isAccept: true },
    ],
    alphabet: ['0', '1'],
    stackAlphabet: ['Z0'],
    startState: 'Q0',
    startStackSymbol: 'Z0',
    acceptStates: ['Q9'],
    transitions: [
      { from: 'Q0', to: 'Q1', input: '1', pop: 'Z0', push: 'Z0' },
      { from: 'Q0', to: 'Q2', input: '0', pop: 'Z0', push: 'Z0' },
      { from: 'Q1', to: 'Q2', input: '0', pop: 'Z0', push: 'Z0' },
      { from: 'Q1', to: 'Q3', input: '1', pop: 'Z0', push: 'Z0' },
      { from: 'Q2', to: 'Q1', input: '1', pop: 'Z0', push: 'Z0' },
      { from: 'Q2', to: 'Q3', input: '0', pop: 'Z0', push: 'Z0' },
      { from: 'Q3', to: 'Q4', input: '0', pop: 'Z0', push: 'Z0' },
      { from: 'Q3', to: 'Q4', input: '1', pop: 'Z0', push: 'Z0' },
      { from: 'Q4', to: 'Q3', input: '0', pop: 'Z0', push: 'Z0' },
      { from: 'Q4', to: 'Q5', input: '1', pop: 'Z0', push: 'Z0' },
      { from: 'Q5', to: 'Q6', input: '0', pop: 'Z0', push: 'Z0' },
      { from: 'Q5', to: 'Q8', input: '1', pop: 'Z0', push: 'Z0' },
      { from: 'Q6', to: 'q4', input: '0', pop: 'Z0', push: 'Z0' }, // Correcting lowercase q from notebook
      { from: 'Q6', to: 'Q9', input: '1', pop: 'Z0', push: 'Z0' },
      { from: 'Q7', to: 'q4', input: '0', pop: 'Z0', push: 'Z0' }, // Correcting lowercase q from notebook
      { from: 'Q7', to: 'Q9', input: '1', pop: 'Z0', push: 'Z0' },
      { from: 'Q8', to: 'Q7', input: '0', pop: 'Z0', push: 'Z0' },
      { from: 'Q8', to: 'Q9', input: '1', pop: 'Z0', push: 'Z0' },
      { from: 'Q9', to: 'Q9', input: '0', pop: 'Z0', push: 'Z0' },
      { from: 'Q9', to: 'Q9', input: '1', pop: 'Z0', push: 'Z0' },
    ].map(t => (t.to === 'q4' ? { ...t, to: 'Q4' } : t))
  },
  pda2: {
    states: [
      { id: 'q0', label: 'q0', isStart: true, isAccept: false },
      { id: 'q1', label: 'q1', isStart: false, isAccept: false },
      { id: 'q2', label: 'q2', isStart: false, isAccept: false },
      { id: 'q3', label: 'q3', isStart: false, isAccept: false },
      { id: 'q4', label: 'q4', isStart: false, isAccept: false },
      { id: 'q5', label: 'q5', isStart: false, isAccept: false },
      { id: 'q6', label: 'q6', isStart: false, isAccept: false },
      { id: 'q7', label: 'q7', isStart: false, isAccept: false },
      { id: 'q8', label: 'q8', isStart: false, isAccept: false },
      { id: 'q9', label: 'q9', isStart: false, isAccept: false },
      { id: 'q10', label: 'q10', isStart: false, isAccept: false },
      { id: 'q11', label: 'q11', isStart: false, isAccept: false },
      { id: 'q12', label: 'q12', isStart: false, isAccept: false },
      { id: 'q13', label: 'q13', isStart: false, isAccept: false },
      { id: 'q14', label: 'q14', isStart: false, isAccept: true },
      { id: 'q15', label: 'q15', isStart: false, isAccept: true },
      { id: 'T', label: 'T', isStart: false, isAccept: false },
    ],
    alphabet: ['a', 'b'],
    stackAlphabet: ['Z0'],
    startState: 'q0',
    startStackSymbol: 'Z0',
    acceptStates: ['q14', 'q15'],
    transitions: [
      { from: 'q0', to: 'q2', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q0', to: 'q1', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q1', to: 'q4', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q1', to: 'q3', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q2', to: 'q3', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q2', to: 'q5', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q3', to: 'q7', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q3', to: 'T', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q4', to: 'q5', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q4', to: 'q6', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q5', to: 'T', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q5', to: 'q8', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q6', to: 'q10', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q6', to: 'q1', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q7', to: 'q9', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q7', to: 'T', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q8', to: 'q10', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q8', to: 'T', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q9', to: 'q11', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q9', to: 'q11', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q10', to: 'q11', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q10', to: 'q11', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q11', to: 'q12', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q11', to: 'q13', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q12', to: 'q14', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q12', to: 'q13', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q13', to: 'q12', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q13', to: 'q15', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q14', to: 'q13', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q14', to: 'q14', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'q15', to: 'q15', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'q15', to: 'q12', input: 'b', pop: 'Z0', push: 'Z0' },
      { from: 'T', to: 'T', input: 'a', pop: 'Z0', push: 'Z0' },
      { from: 'T', to: 'T', input: 'b', pop: 'Z0', push: 'Z0' },
    ]
  },
  pda3: {
    states: [
      { id: 'q0', label: 'q0', isStart: true, isAccept: false },
      { id: 'q1', label: 'q1', isStart: false, isAccept: false },
      { id: 'q2', label: 'q2', isStart: false, isAccept: true },
    ],
    alphabet: ['0', '1'],
    stackAlphabet: ['Z0', '0'],
    startState: 'q0',
    startStackSymbol: 'Z0',
    acceptStates: ['q2'],
    transitions: [
      { from: 'q0', to: 'q0', input: '0', pop: '', push: '0' },
      { from: 'q0', to: 'q1', input: '1', pop: '0', push: '' },
      { from: 'q1', to: 'q1', input: '1', pop: '0', push: '' },
      { from: 'q1', to: 'q2', input: '', pop: 'Z0', push: 'Z0' },
    ]
  }
};
