import { DFA } from '../types';

export const DFA1: DFA = {
  states: [
    { id: 'q0', label: 'q0', isStart: true, isAccept: false },
    { id: 'q1', label: 'q1', isStart: false, isAccept: false },
    { id: 'q2', label: 'q2', isStart: false, isAccept: false },
    { id: 'q3', label: 'q3', isStart: false, isAccept: false },
    { id: 'q4', label: 'q4', isStart: false, isAccept: false },
    { id: 'q5', label: 'q5', isStart: false, isAccept: false },
    { id: 'q6', label: 'q6', isStart: false, isAccept: false },
    { id: 'q7', label: 'q7', isStart: false, isAccept: false },
    { id: 'q8', label: 'q8', isStart: false, isAccept: false },
    { id: 'q9', label: 'q9', isStart: false, isAccept: true },
  ],
  alphabet: ['0', '1'],
  transitions: [
    { from: 'q0', to: 'q1', symbol: '1' },
    { from: 'q0', to: 'q2', symbol: '0' },
    { from: 'q1', to: 'q2', symbol: '0' },
    { from: 'q1', to: 'q3', symbol: '1' },
    { from: 'q2', to: 'q1', symbol: '1' },
    { from: 'q2', to: 'q3', symbol: '0' },
    { from: 'q3', to: 'q4', symbol: '0' },
    { from: 'q3', to: 'q4', symbol: '1' },
    { from: 'q4', to: 'q3', symbol: '0' },
    { from: 'q4', to: 'q5', symbol: '1' },
    { from: 'q5', to: 'q6', symbol: '0' },
    { from: 'q5', to: 'q8', symbol: '1' },
    { from: 'q6', to: 'q4', symbol: '0' },
    { from: 'q6', to: 'q9', symbol: '1' },
    { from: 'q7', to: 'q4', symbol: '0' },
    { from: 'q7', to: 'q9', symbol: '1' },
    { from: 'q8', to: 'q7', symbol: '0' },
    { from: 'q8', to: 'q9', symbol: '1' },
    { from: 'q9', to: 'q9', symbol: '0' },
    { from: 'q9', to: 'q9', symbol: '1' },
  ]
};

export const DFA2: DFA = {
  states: [
    { id: 'q0', label: 'q0', isStart: true, isAccept: false },
    { id: 'q1', label: 'q1', isStart: false, isAccept: false },
    { id: 'q2', label: 'q2', isStart: false, isAccept: false },
    { id: 'q3', label: 'q3', isStart: false, isAccept: false },
    { id: 'q4', label: 'q4', isStart: false, isAccept: false },
    { id: 'q5', label: 'q5', isStart: false, isAccept: false },
    { id: 'q6', label: 'q6', isStart: false, isAccept: false },
    { id: 'q7', label: 'q7', isStart: false, isAccept: false },
    { id: 'q8', label: 'q8', isStart: false, isAccept: false },
    { id: 'q9', label: 'q9', isStart: false, isAccept: false },
    { id: 'q10', label: 'q10', isStart: false, isAccept: false },
    { id: 'q11', label: 'q11', isStart: false, isAccept: false },
    { id: 'q12', label: 'q12', isStart: false, isAccept: false },
    { id: 'q13', label: 'q13', isStart: false, isAccept: false },
    { id: 'q14', label: 'q14', isStart: false, isAccept: true },
    { id: 'q15', label: 'q15', isStart: false, isAccept: true },
    { id: 'T', label: 'T', isStart: false, isAccept: false },
  ],
  alphabet: ['a', 'b'],
  transitions: [
    { from: 'q0', to: 'q2', symbol: 'a' },
    { from: 'q0', to: 'q1', symbol: 'b' },
    { from: 'q1', to: 'q4', symbol: 'a' },
    { from: 'q1', to: 'q3', symbol: 'b' },
    { from: 'q2', to: 'q3', symbol: 'b' },
    { from: 'q2', to: 'q5', symbol: 'a' },
    { from: 'q3', to: 'q7', symbol: 'a' },
    { from: 'q3', to: 'T', symbol: 'b' },
    { from: 'q4', to: 'q5', symbol: 'a' },
    { from: 'q4', to: 'q6', symbol: 'b' },
    { from: 'q5', to: 'T', symbol: 'a' },
    { from: 'q5', to: 'q8', symbol: 'b' },
    { from: 'q6', to: 'q10', symbol: 'a' },
    { from: 'q6', to: 'q1', symbol: 'b' },
    { from: 'q7', to: 'q9', symbol: 'b' },
    { from: 'q7', to: 'T', symbol: 'a' },
    { from: 'q8', to: 'q10', symbol: 'a' },
    { from: 'q8', to: 'T', symbol: 'b' },
    { from: 'q9', to: 'q11', symbol: 'a' },
    { from: 'q9', to: 'q11', symbol: 'b' },
    { from: 'q10', to: 'q11', symbol: 'a' },
    { from: 'q10', to: 'q11', symbol: 'b' },
    { from: 'q11', to: 'q12', symbol: 'b' },
    { from: 'q11', to: 'q13', symbol: 'a' },
    { from: 'q12', to: 'q14', symbol: 'b' },
    { from: 'q12', to: 'q13', symbol: 'a' },
    { from: 'q13', to: 'q12', symbol: 'b' },
    { from: 'q13', to: 'q15', symbol: 'a' },
    { from: 'q14', to: 'q13', symbol: 'a' },
    { from: 'q14', to: 'q14', symbol: 'b' },
    { from: 'q15', to: 'q15', symbol: 'a' },
    { from: 'q15', to: 'q12', symbol: 'b' },
    { from: 'T', to: 'T', symbol: 'a' },
    { from: 'T', to: 'T', symbol: 'b' },
  ]
};

export const DFA_EXAMPLES = {
  dfa1: DFA1,
  dfa2: DFA2
};
